import { build } from "esbuild"
import assert from "node:assert/strict"
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { test } from "node:test"
import { fileURLToPath, pathToFileURL } from "node:url"
import ts from "typescript"

import { ActorCompiler } from "../actor-compiler.js"

import { generateTypeScript } from "./typescript-generator.js"

test("generates backend grants without a frontend socket client", async () => {
    const code = (await generateTypeScript({ version: 1, actors: [] })).get("index.ts")!
    assert.doesNotMatch(code, /createClient|namespace clients|const clients|little-actors\/browser/)
})

test("formats generated sections and provides concise usage examples", async t => {
    const root = await project(t)
    const entrypoint = path.join(root, "actors.ts")
    await writeFile(
        entrypoint,
        `
        import { Actor, Persisted } from "little-actors"
        export class Room extends Actor<{ userId: string }, string, never> {
            @Persisted history: string[] = []
            async clear(): Promise<void> {}
        }
    `
    )
    const code = (await generateTypeScript(new ActorCompiler().compileContract(entrypoint))).get("index.ts")!
    assert.match(code, /^\/\/ Generated by little-actors; regenerate instead of editing\./)
    assert.match(
        code,
        /Use this file to call actors and prepare WebSocket access from your backend\.\n \* @example\n \* import \{ actors, ActorProxy, type ActorAuthorization \} from "\.\/generated\/index\.js"/
    )
    assert.match(code, /namespace actors \{\n    export namespace Room \{/)
    assert.match(code, /        history: string\[\]/)
    assert.match(
        code,
        /Types for actor state and methods[\s\S]*?type State = actors.Room.State[\s\S]*?\*\/\nexport declare namespace actors/
    )
    assert.match(
        code,
        /Call actor methods from your backend[\s\S]*?const actor = actors.Room.get\("actor-id"\)[\s\S]*?\*\/\nexport const actors/
    )
    assert.match(
        code,
        /Types for a method's arguments and return value[\s\S]*?actors.Room.Methods\["clear"\]\["Args"\]/
    )
    assert.match(
        code,
        /Allow a frontend connection after your backend checks the user's access[\s\S]*?await ActorProxy.handle\(\{ actorType: "Room", actorId: "actor-id", metadata \}\)[\s\S]*?\*\/\nexport class ActorProxy/
    )
    await checkUsageExamples(root, code)
})

test("preserves authored state types and inlines anonymous shapes from stored contracts", async t => {
    const root = await project(t)
    const entrypoint = path.join(root, "actors.ts")
    await writeFile(
        entrypoint,
        `
        import { Actor, Persisted, Emittable } from "little-actors"
        declare global { interface Array<T> {} }
        type ChatMessage = { name: string; text: string }
        type Author = { name: string }
        type Thread = { message: ChatMessage; reply?: Thread; author?: Author }
        type Stub = { id: string }
        export class ChatRoom extends Actor<{}, never, never> {
            @Persisted @Emittable history: ChatMessage[] = []
            @Persisted drafts: { text: string }[] = []
            @Persisted stub: Stub = { id: "one" }
            @Persisted threads: Thread[] = []
            async latest(): Promise<ChatMessage> { return { name: "Ada", text: "hi" } }
        }
    `
    )
    const contract = JSON.parse(JSON.stringify(new ActorCompiler().compileContract(entrypoint)))
    const code = (await generateTypeScript(contract)).get("index.ts")!
    assert.match(code, /history: ChatMessage\[\]/)
    assert.doesNotMatch(code, /export (?:type|interface) Type\d+\b/)
    await writeFile(path.join(root, "index.ts"), code)
    await writeFile(
        path.join(root, "consumer.ts"),
        `
        import { actors } from "./index.js"
        const message: actors.ChatRoom.ChatMessage = { name: "Ada", text: "hi" }
        const history: actors.ChatRoom.State["history"] = [message]
        const drafts: actors.ChatRoom.State["drafts"] = [{ text: "draft" }]
        const stub: actors.ChatRoom.Stub = { id: "one" }
        const thread: actors.ChatRoom.Thread = { message, reply: { message } }
        const author: actors.ChatRoom.Author = { name: "Ada" }
        const latest: Promise<actors.ChatRoom.ChatMessage> = actors.ChatRoom.get("lobby").latest()
        // @ts-expect-error authored property types are preserved
        const wrong: actors.ChatRoom.ChatMessage = { name: 1, text: "hi" }
    `
    )
    checkTypes(path.join(root, "consumer.ts"))
})

test("keeps state type names distinct from contract roots and RPC types", async t => {
    const root = await project(t)
    await writeFile(path.join(root, "first.ts"), "export type Item = { value: string }")
    await writeFile(path.join(root, "second.ts"), "export type Item = { value: number }")
    const entrypoint = path.join(root, "actors.ts")
    await writeFile(
        entrypoint,
        `
        import { Actor, Persisted } from "little-actors"
        import type { Item as First } from "./first.js"
        import type { Item as Second } from "./second.js"
        type State = { id: string }
        type ItemData = { other: boolean }
        export class Room extends Actor<State, never, never> {
            @Persisted items: First[] = []
            @Persisted data: ItemData[] = []
            async echo(input: Second): Promise<Second> { return input }
        }
    `
    )
    const code = (await generateTypeScript(new ActorCompiler().compileContract(entrypoint))).get("index.ts")!
    await writeFile(path.join(root, "index.ts"), code)
    await writeFile(
        path.join(root, "consumer.ts"),
        `
        import { actors } from "./index.js"
        const metadata: actors.Room.Metadata = { id: "one" }
        const item: actors.Room.Item = { value: "one" }
        const state: actors.Room.State = { items: [item], data: [{ other: true }] }
        const input: actors.Room.Methods.echo.Args = [{ value: 1 }]
        // @ts-expect-error same source names must not merge different types
        const wrong: actors.Room.Methods.echo.Args = [item]
    `
    )
    checkTypes(path.join(root, "consumer.ts"))
})

test("groups public state and method arguments and results under each actor", async t => {
    const root = await project(t)
    const entrypoint = path.join(root, "actors.ts")
    await writeFile(
        entrypoint,
        `
        import { Actor, Persisted, Emittable } from "little-actors"
        type State = { id: number }
        type Methods = { label: string }
        type Parameters = { count: number }
        type ReturnType = { text: string }
        type Awaited = { done: boolean }
        export class ChatRoom extends Actor<{ userId: string }, string, never> {
            @Persisted @Emittable history: string[] = []
            @Persisted private secret = "hidden"
            async ClearHistoryKeepLast(keep: number, reason?: string): Promise<number> { return keep }
            async count(scale = 1) { return scale }
            async tags(...tags: string[]) { return tags }
            async clear(): Promise<void> {}
            async fail(): Promise<never> { throw new Error("failed") }
            async named(input: State): Promise<Methods> { return { label: String(input.id) } }
            async ["clear-history"]() { return 1 }
            async Methods() { return 1 }
            async utilityNames(input: Parameters, output: ReturnType): Promise<Awaited> { return { done: input.count > 0 } }
            private async hidden() {}
        }
    `
    )
    const files = await generateTypeScript(new ActorCompiler().compileContract(entrypoint))
    assert.deepEqual([...files.keys()], ["index.ts"])
    await writeFile(path.join(root, "index.ts"), files.get("index.ts")!)
    await writeFile(
        path.join(root, "consumer.ts"),
        `
        import { actors } from "./index.js"
        type History = actors.ChatRoom.State["history"]
        type Args = actors.ChatRoom.Methods.ClearHistoryKeepLast.Args
        type Result = actors.ChatRoom.Methods.ClearHistoryKeepLast.Result
        const history: History = ["hello"]
        const state: actors.ChatRoom.State = { history }
        const args: Args = [2]
        const reason: Args = [2, "cleanup"]
        const result: Result = 2
        const called: Promise<Result> = actors.ChatRoom.get("lobby").ClearHistoryKeepLast(...args)
        const defaults: actors.ChatRoom.Methods.count.Args = []
        const tags: actors.ChatRoom.Methods.tags.Args = ["one", "two"]
        const cleared: actors.ChatRoom.Methods.clear.Result = undefined
        declare const failure: actors.ChatRoom.Methods.fail.Result
        const never: never = failure
        const input: actors.ChatRoom.Methods.named.Args = [{ id: 1 }]
        const output: actors.ChatRoom.Methods.named.Result = { label: "one" }
        const unusual: actors.ChatRoom.Methods["clear-history"]["Args"] = []
        const colliding: actors.ChatRoom.Methods.Methods.Result = 1
        const utilityArgs: actors.ChatRoom.Methods.utilityNames.Args = [{ count: 1 }, { text: "ok" }]
        const utilityResult: actors.ChatRoom.Methods.utilityNames.Result = { done: true }
        // @ts-expect-error arguments retain their types
        const wrong: Args = ["two"]
        // @ts-expect-error the first argument is required
        const missing: Args = []
        // @ts-expect-error Result is the resolved value
        const promise: Result = Promise.resolve(2)
        // @ts-expect-error private state is excluded
        type Secret = actors.ChatRoom.State["secret"]
        // @ts-expect-error private methods are excluded
        type Hidden = actors.ChatRoom.Methods.hidden.Args
    `
    )
    checkTypes(path.join(root, "consumer.ts"))
})

test("preserves named RPC types and their dependencies in clients generated from stored contracts", async t => {
    const author = await project(t)
    const entrypoint = path.join(author, "actors.ts")
    await writeFile(
        entrypoint,
        `
        import { Actor } from "little-actors"
        interface Author { name: string }
        interface Message { text: string; author: Author; reply?: Message }
        type SendMessageInput = { text: string }
        export class ChatRoom extends Actor<{}, never, never> {
            async sendMessage(input: SendMessageInput): Promise<Message> {
                return { text: input.text, author: { name: "Ada" } }
            }
            async latest(): Promise<Message> { return this.sendMessage({ text: "hi" }) }
        }
    `
    )
    const contract = JSON.parse(JSON.stringify(new ActorCompiler().compileContract(entrypoint)))
    await rm(author, { recursive: true, force: true })
    const files = await generateTypeScript(contract)
    const code = files.get("index.ts")!
    assert.match(code, /export interface SendMessageInput\b/)
    assert.match(code, /export interface Message\b/)
    assert.match(code, /export interface Author\b/)
    assert.match(code, /sendMessage\(input: SendMessageInput\): Promise<Message>/)
    assert.match(code, /latest\(\): Promise<Message>/)
    assert.match(code, /reply\?: Message/)
    const consumer = await project(t)
    for (const [file, content] of files) await writeFile(path.join(consumer, file), content)
    checkTypes(path.join(consumer, "index.ts"))
})

test("names anonymous RPC types from methods and parameters in existing published contracts", async t => {
    const contract = JSON.parse(
        await readFile(new URL("../../../../fixtures/public-contract.json", import.meta.url), "utf8")
    )
    const files = await generateTypeScript(contract)
    const code = files.get("index.ts")!
    assert.match(code, /export interface SendMessageInput\b/)
    assert.match(code, /export interface SendMessageResult\b/)
    assert.match(code, /sendMessage\(input: SendMessageInput\): Promise<SendMessageResult>/)
    const consumer = await project(t)
    for (const [file, content] of files) await writeFile(path.join(consumer, file), content)
    checkTypes(path.join(consumer, "index.ts"))
})

test("disambiguates source type names without merging distinct RPC types or generated helpers", async t => {
    const root = await project(t)
    await writeFile(path.join(root, "first.ts"), "export interface Item { value: string }")
    await writeFile(path.join(root, "second.ts"), "export interface Item { value: number }")
    const entrypoint = path.join(root, "actors.ts")
    await writeFile(
        entrypoint,
        `
        import { Actor } from "little-actors"
        import type { Item as First } from "./first.js"
        import type { Item as Second } from "./second.js"
        type Stub = { stub: boolean }
        type RpcTypes = { rpc: boolean }
        export class Room extends Actor<{}, never, never> {
            async first(input: First): Promise<First> { return input }
            async second(input: Second): Promise<Second> { return input }
            async helpers(input: Stub): Promise<RpcTypes> { return { rpc: input.stub } }
        }
    `
    )
    const files = await generateTypeScript(JSON.parse(JSON.stringify(new ActorCompiler().compileContract(entrypoint))))
    const code = files.get("index.ts")!
    assert.match(code, /export interface Item\b/)
    assert.match(code, /first\(input: Item\): Promise<Item>/)
    for (const [file, content] of files) await writeFile(path.join(root, file), content)
    await writeFile(
        path.join(root, "consumer.ts"),
        `
        import { actors } from "./index.js"
        const room = actors.Room.get("one")
        const first: Promise<{ value: string }> = room.first({ value: "one" })
        const second: Promise<{ value: number }> = room.second({ value: 1 })
        const helpers: Promise<{ rpc: boolean }> = room.helpers({ stub: true })
        // @ts-expect-error distinct types with the same source name
        room.first({ value: 1 })
        // @ts-expect-error distinct types with the same source name
        room.second({ value: "one" })
    `
    )
    checkTypes(path.join(root, "consumer.ts"))
})

test("generates callable typed backend stubs in a consumer without actor source or private dependencies", async t => {
    const author = await project(t)
    await mkdir(path.join(author, "node_modules/private-data"))
    await writeFile(
        path.join(author, "node_modules/private-data/package.json"),
        JSON.stringify({ types: "index.d.ts" })
    )
    await writeFile(
        path.join(author, "node_modules/private-data/index.d.ts"),
        "export interface Message { text: string; reply?: Message }"
    )
    const entrypoint = path.join(author, "actors.ts")
    await writeFile(
        entrypoint,
        `
        import { Actor } from "little-actors"
        import type { Message } from "private-data"
        export class ChatRoom extends Actor<{}, never, never> {
            async sendMessage(input: Message): Promise<Message> { return input }
            async clear(): Promise<void> {}
            async count(scale = 1): Promise<number> { return scale }
            async tags(...tags: string[]): Promise<string[]> { return tags }
            async nullable(): Promise<null> { return null }
            private async secret() {}
        }
        throw new Error("must never execute")
    `
    )
    const contract = JSON.parse(JSON.stringify(new ActorCompiler().compileContract(entrypoint)))
    await rm(author, { recursive: true, force: true })
    const files = await generateTypeScript(contract)
    assert.ok(files.has("index.ts"))
    const consumer = await project(t)
    for (const [file, content] of files) await writeFile(path.join(consumer, file), content)
    await writeFile(
        path.join(consumer, "consumer.ts"),
        `
        import { actors } from "./index.js"
        const room = actors.ChatRoom.get("room-123")
        const grant: Promise<{ websocketUrl: string; transport: "websocket"; homeRegion: string; connectByMs: number; authorizedUntilMs: number }> = actors.ChatRoom.prepareWebsocket({ actorId: "room-123", metadata: {} })
        const message: Promise<{ text: string; reply?: { text: string } }> = room.sendMessage({ text: "hi" })
        const cleared: Promise<void> = room.clear()
        const count: Promise<number> = room.count()
        const tags: Promise<string[]> = room.tags("one", "two")
        const nullable: Promise<null> = room.nullable()
        // @ts-expect-error wrong argument type
        room.sendMessage({ text: 123 })
        // @ts-expect-error required argument
        room.sendMessage()
        // @ts-expect-error private method
        room.secret()
        // @ts-expect-error recursive type
        room.sendMessage({ text: "hi", reply: { text: 123 } })
        // @ts-expect-error wrong result type
        const wrong: Promise<string> = room.count()
        // @ts-expect-error wrong rest type
        room.tags(123)
    `
    )
    checkTypes(path.join(consumer, "consumer.ts"))
    const outfile = path.join(consumer, "backend.mjs")
    const bundled = await build({
        entryPoints: [path.join(consumer, "index.ts")],
        outfile,
        bundle: true,
        format: "esm",
        platform: "node",
        external: ["little-actors/generated"],
        metafile: true
    })
    assert.equal(
        Object.keys(bundled.metafile!.inputs).some(file => file.includes("private-data")),
        false
    )
    const { actors } = await import(pathToFileURL(outfile).href)
    const calls: unknown[][] = []
    const room = actors.ChatRoom.get("room-123", {
        async invoke(...args: unknown[]) {
            calls.push(args)
            return args[2] === "sendMessage" ? { text: "hi" } : null
        }
    })
    assert.deepEqual(await room.sendMessage({ text: "hi" }), { text: "hi" })
    assert.equal(await room.clear(), undefined)
    assert.equal(await room.nullable(), null)
    assert.deepEqual(calls[0], ["ChatRoom", "room-123", "sendMessage", [{ text: "hi" }]])
    const browser = await build({
        entryPoints: [path.join(consumer, "index.ts")],
        bundle: true,
        platform: "browser",
        format: "esm",
        write: false,
        metafile: true
    })
    assert.equal(
        Object.keys(browser.metafile!.inputs).some(file =>
            /\/(?:backend\.js|proxy\.js|client\/|@grpc\/|typescript\/|private-data\/)|node:/.test(file)
        ),
        false
    )
    const browserModule = await import(
        `data:text/javascript;base64,${Buffer.from(browser.outputFiles![0]!.text).toString("base64")}`
    )
    assert.equal(browserModule.clients, undefined)
    assert.throws(() => browserModule.actors.ChatRoom.get("room-123"), /server/)
    assert.throws(() => browserModule.actors.ChatRoom.prepareWebsocket({ actorId: "room-123", metadata: {} }), /server/)
    assert.throws(() => new browserModule.ActorProxy(), /server/)
})

test("generated modules handle actor/helper collisions, duplicate argument labels and never results", async t => {
    const root = await project(t)
    const entrypoint = path.join(root, "actors.ts")
    await writeFile(
        entrypoint,
        `
        import { Actor } from "little-actors"
        export class Stub extends Actor<{}, never, never> {
            async fail(): Promise<never> { throw new Error("failed") }
            async unpack({ value }: { value: number }, arg0: string) { return value }
            async __proto__() { return 1 }
        }
        export class RpcTypes extends Actor<{}, never, never> { async clear() {} }
        export class backend extends Actor<{}, never, never> {}
    `
    )
    const files = await generateTypeScript(new ActorCompiler().compileContract(entrypoint))
    for (const [file, content] of files) await writeFile(path.join(root, file), content)
    await writeFile(
        path.join(root, "consumer.ts"),
        `
        import { actors } from "./index.js"
        const never: Promise<never> = actors.Stub.get("one").fail()
        const value: Promise<number> = actors.Stub.get("one").unpack({ value: 1 }, "text")
        const proto: Promise<number> = actors.Stub.get("one").__proto__()
        const cleared: Promise<void> = actors.RpcTypes.get("one").clear()
        actors.backend.get("one")
    `
    )
    checkTypes(path.join(root, "consumer.ts"))
})

test("public contracts reject unsupported versions and generate an empty backend module", async () => {
    const files = await generateTypeScript({ version: 1, actors: [] })
    assert.match(files.get("index.ts")!, /export const actors = \{\s*\}/)
    await assert.rejects(generateTypeScript({ version: 2, actors: [] } as never), /version/)
})

async function project(t: { after(fn: () => Promise<void>): void }) {
    const root = await mkdtemp(path.join(os.tmpdir(), "backend-codegen-"))
    t.after(() => rm(root, { recursive: true, force: true }))
    await mkdir(path.join(root, "node_modules"))
    const location = fileURLToPath(new URL("../../../", import.meta.url))
    const sdk = location.endsWith(`${path.sep}.test-dist${path.sep}`) ? path.dirname(location.slice(0, -1)) : location
    await symlink(sdk, path.join(root, "node_modules/little-actors"))
    await writeFile(path.join(root, "package.json"), JSON.stringify({ type: "module" }))
    return root
}

async function checkUsageExamples(root: string, code: string) {
    const examples = [...code.matchAll(/@example\n((?:[ \t]*\* .*\n)+)/g)].map(match =>
        match[1]!.replace(/^[ \t]*\* /gm, "").trim()
    )
    const [imports, ...snippets] = examples
    await mkdir(path.join(root, "generated"))
    await writeFile(path.join(root, "generated/index.ts"), code)
    const consumer = path.join(root, "usage.ts")
    await writeFile(
        consumer,
        `${imports}\ndeclare const metadata: actors.Room.Metadata\n${snippets.map(example => `{\n${example}\n}`).join("\n")}`
    )
    checkTypes(consumer)
}

function checkTypes(entrypoint: string) {
    const program = ts.createProgram([entrypoint], {
        strict: true,
        noEmit: true,
        skipLibCheck: true,
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.NodeNext
    })
    assert.deepEqual(
        ts
            .getPreEmitDiagnostics(program)
            .map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n")),
        []
    )
}
