import { format } from "prettier"
import ts from "typescript"

import { runtimeFiles } from "../../generated/client-runtime.js"
import type { SocketContract } from "../../wire/contract.js"
import type { PublicActorContract } from "../../wire/public-contract.js"
import { parsePublicContract } from "../validate-public-contract.js"

import { backendSource } from "./backend-generator.js"
import { usageComment } from "./usage-comment.js"

/** Returns JavaScript and TypeScript declarations with a standalone runtime, without writing files or executing actor code. */
async function generateClientArtifacts(input: PublicActorContract): Promise<ReadonlyMap<string, string>> {
    const document = parsePublicContract(input)
    const contracts = document.actors.map(actor => actor.socket)
    const declarations = contracts.map(contract => actorDeclarations(contract))
    const exampleActor = contracts[0]?.actorName
    const source = `${usageComment("Use this file to call actors and prepare WebSocket access from your backend.", 'import { actors, ActorProxy, type ActorAuthorization } from "./generated/index.js"')}
import { createActorStub as $createActorStub, SocketProxy as $SocketProxy } from "./runtime/index.js"
import type { ActorTypes as $ActorTypes } from "./types.js"
export { createActorTransport, ActorInvocationError } from "./runtime/index.js"
export type { ActorRpcTransport, DurableActorsClientOptions, SocketGrant, SocketProxyDependencies, SocketProxyOptions } from "./runtime/index.js"

${usageComment("Types for actor state and socket messages.", exampleActor && `type State = actors.${exampleActor}.State`)}
export declare namespace actors {
${declarations.join("\n")}
}

${backendSource(document.actors)}
${proxySource(contracts)}`
    return clientArtifacts(source, document.typescript)
}

async function clientArtifacts(
    source: string,
    typescript: PublicActorContract["typescript"]
): Promise<ReadonlyMap<string, string>> {
    const options = { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext }
    const javascript = ts.transpileModule(source, { compilerOptions: options, fileName: "index.ts" })
    const declaration = ts.transpileDeclaration(source, { compilerOptions: options, fileName: "index.ts" })
    if (declaration.diagnostics?.length)
        throw new Error(
            declaration.diagnostics.map(d => ts.flattenDiagnosticMessageText(d.messageText, "\n")).join("\n")
        )
    return new Map([
        ["index.js", await formatSource(javascript.outputText)],
        ["index.d.ts", await formatSource(declaration.outputText)],
        ["types.d.ts", await formatSource(typescript.declarations)],
        [
            "package.json",
            JSON.stringify({ private: true, type: "module", peerDependencies: typescript.dependencies }, null, 2) + "\n"
        ],
        ...Object.entries(runtimeFiles)
    ])
}

function formatSource(source: string): Promise<string> {
    return format(`// Generated by durable-actors; regenerate instead of editing.\n${source}`, {
        parser: "typescript",
        tabWidth: 4,
        printWidth: 120,
        semi: false,
        trailingComma: "none"
    })
}

function actorDeclarations(contract: SocketContract): string {
    return `export namespace ${contract.actorName} {
${["Metadata", "Incoming", "Outgoing", "State"].map(kind => `export type ${kind} = $ActorTypes[${JSON.stringify(contract.actorName)}][${JSON.stringify(kind)}]`).join("\n")}
export interface Authorization {
    actorName: ${JSON.stringify(contract.actorName)}
    actorId: string
    metadata: Metadata
    clientLocation?: { latitude: number; longitude: number }
    authorizationLifetimeMs?: number
}
}`
}

function proxySource(contracts: readonly SocketContract[]): string {
    const actors = contracts
        .map(
            ({ actorName }) =>
                `[${JSON.stringify(actorName)}]: {} as import("./runtime/index.js").ProxyActor<actors.${actorName}.Metadata>`
        )
        .join(", ")
    const authorization = contracts.map(({ actorName }) => `actors.${actorName}.Authorization`).join(" | ") || "never"
    const exampleActor = contracts[0]?.actorName
    return `${usageComment("The actor and connection details approved by your backend.", exampleActor && `const authorization: ActorAuthorization = { actorName: ${JSON.stringify(exampleActor)}, actorId: "actor-id", metadata }`)}
export type ActorAuthorization = ${authorization}

${usageComment("Allow a frontend connection after your backend checks the user's access.", exampleActor && `const grant = await ActorProxy.handle({ actorName: ${JSON.stringify(exampleActor)}, actorId: "actor-id", metadata })`)}
export class ActorProxy extends $SocketProxy<{
${contracts.map(({ actorName }) => `[${JSON.stringify(actorName)}]: import("./runtime/index.js").ProxyActor<actors.${actorName}.Metadata>`).join("\n")}
}> {
    constructor(options: import("./runtime/index.js").SocketProxyOptions = {}, dependencies: import("./runtime/index.js").SocketProxyDependencies = {}) {
        super({ ${actors} }, options, dependencies)
    }

    handle(authorization: ActorAuthorization): Promise<import("./runtime/index.js").SocketGrant> {
        return super.handle(authorization)
    }

    static handle(authorization: ActorAuthorization, options: import("./runtime/index.js").SocketProxyOptions = {}): Promise<import("./runtime/index.js").SocketGrant> {
        return new ActorProxy(options).handle(authorization)
    }
}
`
}

export { generateClientArtifacts }
export type { PublicActorContract }
