import { compile } from "json-schema-to-typescript"
import type { JSONSchema } from "json-schema-to-typescript"
import { format } from "prettier"
import ts from "typescript"

import type { SocketContract } from "../../wire/contract.js"
import type { PublicActorContract } from "../../wire/public-contract.js"
import { parsePublicContract } from "../validate-public-contract.js"

import { backendSource } from "./backend-generator.js"
import { runtimeArtifacts } from "./runtime-generator.js"
import { usageComment } from "./usage-comment.js"

/** Returns standalone client artifacts without writing files or executing actor code. */
async function generateTypeScript(
    input: readonly SocketContract[] | PublicActorContract
): Promise<ReadonlyMap<string, string>> {
    const document = "actors" in input ? input : undefined
    if (document && document.version !== 1)
        throw new Error(`unsupported public actor contract version ${document.version}`)
    if (document) parsePublicContract(document)
    const contracts = "actors" in input ? input.actors.map(actor => actor.socket) : input
    const declarations: string[] = []
    const wireNames = new Map<string, readonly string[]>()
    for (const contract of contracts) {
        if (!/^[A-Za-z_$][\w$]*$/u.test(contract.actorName))
            throw new Error(`actor name ${contract.actorName} cannot be emitted as a TypeScript identifier`)
        const wire = await wireDeclarations(contract)
        wireNames.set(contract.actorName, [...wire.names, "Authorization"])
        declarations.push(actorDeclarations(contract, wire.code))
    }
    const exampleActor = contracts[0]?.actorName
    const source = `// Generated by durable-actors; regenerate instead of editing.
${usageComment("Use this file to call actors and prepare WebSocket access from your backend.", 'import { actors, ActorProxy, type ActorAuthorization } from "./generated/index.js"')}
import { createActorStub as $createActorStub, SocketProxy as $SocketProxy } from "./runtime/index.js"

${usageComment("Types for actor state and socket messages.", exampleActor && `type State = actors.${exampleActor}.State`)}
export declare namespace actors {
${declarations.join("\n")}
}

${await backendSource(document?.actors ?? [], contracts, wireNames)}
${proxySource(contracts)}`
    const formatted = await format(source, {
        parser: "typescript",
        tabWidth: 4,
        printWidth: 120,
        semi: false,
        trailingComma: "none"
    })
    return new Map([["index.ts", formatted], ...(await runtimeArtifacts())])
}

function actorDeclarations(contract: SocketContract, declarations: string): string {
    return `export namespace ${contract.actorName} {
${declarations}
export interface Authorization {
    actorName: ${JSON.stringify(contract.actorName)}
    actorId: string
    metadata: Metadata
    clientLocation?: { latitude: number; longitude: number }
    authorizationLifetimeMs?: number
}
}`
}

async function wireDeclarations(contract: SocketContract) {
    const kinds = ["Metadata", "Incoming", "Outgoing", "State"]
    const properties = Object.fromEntries(
        kinds.map(kind => [
            kind.toLowerCase(),
            typeof contract.schema.definitions?.[kind] === "boolean"
                ? contract.schema.definitions[kind]
                : { $ref: `#/definitions/${kind}` }
        ])
    )
    const code = await compile(
        inlineAnonymousReferences(
            {
                ...contract.schema,
                type: "object",
                additionalProperties: false,
                properties,
                required: Object.keys(properties)
            },
            contract.schema.definitions ?? {}
        ) as JSONSchema,
        "ActorTypes",
        {
            $refOptions: { resolve: { file: false, http: false } },
            bannerComment: "",
            unknownAny: true,
            additionalProperties: false,
            customName: (schema, key) => {
                const name = schema.title || schema.$id || key
                return (schema.title && kinds.includes(name)) ||
                    ["Connection", "Authorization", "Methods", "Parameters", "ReturnType", "Awaited"].includes(name)
                    ? `${name}Data`
                    : undefined
            }
        }
    )
    const source = ts.createSourceFile("types.ts", code, ts.ScriptTarget.Latest, true)
    const root = source.statements.find(
        statement => ts.isInterfaceDeclaration(statement) && statement.name.text === "ActorTypes"
    ) as ts.InterfaceDeclaration
    const declarations = source.statements.filter(statement => statement !== root)
    const named = new Map(
        declarations
            .filter(
                (statement): statement is ts.InterfaceDeclaration | ts.TypeAliasDeclaration =>
                    ts.isInterfaceDeclaration(statement) || ts.isTypeAliasDeclaration(statement)
            )
            .map(statement => [statement.name.text, statement])
    )
    const main = kinds.map(kind => {
        const declaration = named.get(kind)
        if (declaration) return declaration.getText(source)
        const property = root.members.find(
            member => ts.isPropertySignature(member) && member.name.getText(source) === kind.toLowerCase()
        ) as ts.PropertySignature
        return `export type ${kind} = ${property.type!.getText(source)}`
    })
    const helpers = declarations.filter(statement => !kinds.some(kind => named.get(kind) === statement))
    return {
        code: [...main, ...helpers.map(statement => statement.getText(source))].join("\n\n") + "\n",
        names: [...new Set([...kinds, ...named.keys()])]
    }
}

function inlineAnonymousReferences(
    value: unknown,
    definitions: NonNullable<SocketContract["schema"]["definitions"]>,
    visiting = new Set<string>()
): unknown {
    if (Array.isArray(value)) return value.map(item => inlineAnonymousReferences(item, definitions, visiting))
    if (!value || typeof value !== "object") return value
    const node = value as Record<string, unknown>
    const key =
        typeof node.$ref === "string" && node.$ref.startsWith("#/definitions/")
            ? decodeURIComponent(node.$ref.slice("#/definitions/".length)).replaceAll("~1", "/").replaceAll("~0", "~")
            : undefined
    const definition = key === undefined ? undefined : definitions[key]
    if (
        key !== undefined &&
        definition &&
        typeof definition === "object" &&
        !definition.title &&
        !visiting.has(key) &&
        (/^(Type\d+|Field_.*)$/.test(key) ||
            (typeof definition.type === "string" &&
                ["string", "number", "integer", "boolean", "null"].includes(definition.type)))
    ) {
        const { $ref, ...rest } = node
        return inlineAnonymousReferences({ ...definition, ...rest }, definitions, new Set([...visiting, key]))
    }
    return Object.fromEntries(
        Object.entries(node).map(([key, child]) => [key, inlineAnonymousReferences(child, definitions, visiting)])
    )
}

function proxySource(contracts: readonly SocketContract[]): string {
    const actors = contracts
        .map(
            ({ actorName }) =>
                `[${JSON.stringify(actorName)}]: {} as import("./runtime/types.js").ProxyActor<actors.${actorName}.Metadata>`
        )
        .join(", ")
    const authorization = contracts.map(({ actorName }) => `actors.${actorName}.Authorization`).join(" | ") || "never"
    const exampleActor = contracts[0]?.actorName
    return `${usageComment("The actor and connection details approved by your backend.", exampleActor && `const authorization: ActorAuthorization = { actorName: ${JSON.stringify(exampleActor)}, actorId: "actor-id", metadata }`)}
export type ActorAuthorization = ${authorization}

${usageComment("Allow a frontend connection after your backend checks the user's access.", exampleActor && `const grant = await ActorProxy.handle({ actorName: ${JSON.stringify(exampleActor)}, actorId: "actor-id", metadata })`)}
export class ActorProxy extends $SocketProxy<{
${contracts.map(({ actorName }) => `[${JSON.stringify(actorName)}]: import("./runtime/types.js").ProxyActor<actors.${actorName}.Metadata>`).join("\n")}
}> {
    constructor(options: import("./runtime/types.js").SocketProxyOptions = {}, dependencies: import("./runtime/types.js").SocketProxyDependencies = {}) {
        super({ ${actors} }, options, dependencies)
    }

    handle(authorization: ActorAuthorization): Promise<import("./runtime/types.js").SocketGrant> {
        return super.handle(authorization)
    }

    static handle(authorization: ActorAuthorization, options: import("./runtime/types.js").SocketProxyOptions = {}): Promise<import("./runtime/types.js").SocketGrant> {
        return new ActorProxy(options).handle(authorization)
    }
}
`
}

export { generateTypeScript }
export type { SocketContract }
export type { PublicActorContract }
