import { compile } from "json-schema-to-typescript"
import type { JSONSchema } from "json-schema-to-typescript"
import { format } from "prettier"
import ts from "typescript"

import type { SocketContract } from "../../wire/contract.js"
import type { PublicActorContract } from "../../wire/public-contract.js"
import { parsePublicContract } from "../validate-public-contract.js"

import { backendSource } from "./backend-generator.js"
import { usageComment } from "./usage-comment.js"

/** Returns generated filenames and TypeScript source without writing files or executing actor code. */
async function generateTypeScript(
    input: readonly SocketContract[] | PublicActorContract
): Promise<ReadonlyMap<string, string>> {
    const document = "actors" in input ? input : undefined
    if (document && document.version !== 1)
        throw new Error(`unsupported public actor contract version ${document.version}`)
    if (document) parsePublicContract(document)
    const contracts = "actors" in input ? input.actors.map(actor => actor.socket) : input
    const declarations: string[] = []
    const wireNames = new Map<string, readonly string[]>()
    for (const contract of contracts) {
        if (!/^[A-Za-z_$][\w$]*$/u.test(contract.actorType))
            throw new Error(`actor name ${contract.actorType} cannot be emitted as a TypeScript identifier`)
        const wire = await wireDeclarations(contract)
        wireNames.set(contract.actorType, [...wire.names, "Connection", "Authorization"])
        declarations.push(clientDeclarations(contract, wire.code))
    }
    const exampleActor = contracts[0]?.actorType
    const source = `// Generated by little-actors; regenerate instead of editing.
${usageComment("Use this file to call actors from your backend and connect to them from your frontend.", 'import { actors, clients, ActorProxy, type ActorAuthorization } from "./generated/index.js"')}
import { createClient as $createClient, createActorStub as $createActorStub, SocketProxy as $SocketProxy } from "little-actors/generated"

${usageComment("Types for frontend connections and messages.", exampleActor && `type Connection = clients.${exampleActor}.Connection`)}
export declare namespace clients {
${declarations.join("\n")}
}

${clientSource(contracts)}
${await backendSource(document?.actors ?? [], contracts, wireNames)}
${proxySource(contracts)}`
    const formatted = await format(source, {
        parser: "typescript",
        tabWidth: 4,
        printWidth: 120,
        semi: false,
        trailingComma: "none"
    })
    return new Map([["index.ts", formatted]])
}

function clientDeclarations(contract: SocketContract, declarations: string): string {
    const fields = contract.emittable.map(field => JSON.stringify(field)).join(" | ") || "never"
    return `export namespace ${contract.actorType} {
${declarations}
export type Connection = import("little-actors/browser").ActorConnection<Incoming, Outgoing, State, ${fields}>
export interface Authorization {
    actorType: ${JSON.stringify(contract.actorType)}
    actorId: string
    metadata: Metadata
    authorizationLifetimeMs?: number
}
}`
}

function clientSource(contracts: readonly SocketContract[]): string {
    const actors = contracts.map(contract => {
        const types = `clients.${contract.actorType}`
        const fields = contract.emittable.map(field => JSON.stringify(field)).join(" | ") || "never"
        return `[${JSON.stringify(contract.actorType)}]: {
    get(actorId: string, options: import("little-actors/browser").ClientOptions = {}): ${types}.Connection {
        const descriptor: import("little-actors/browser").ActorDescriptor<${types}.Incoming, ${types}.Outgoing, ${types}.State, ${fields}> = {
            actorType: ${JSON.stringify(contract.actorType)}, emittable: ${JSON.stringify(contract.emittable)}
        }
        return $createClient({ actor: descriptor }, options).actor.get(actorId)
    }
}`
    })
    const exampleActor = contracts[0]?.actorType
    return `${usageComment("Connect to an actor from your frontend.", exampleActor && `const client = clients.${exampleActor}.get("actor-id")\nawait client.connect()`)}
export const clients = {\n${actors.join(",\n")}\n}\n`
}

async function wireDeclarations(contract: SocketContract) {
    const kinds = ["Metadata", "Incoming", "Outgoing", "State"]
    const properties = Object.fromEntries(
        kinds.map(kind => [
            kind.toLowerCase(),
            typeof contract.schema.definitions?.[kind] === "boolean"
                ? contract.schema.definitions[kind]
                : { $ref: `#/definitions/${kind}` }
        ])
    )
    const code = await compile(
        inlineAnonymousReferences(
            {
                ...contract.schema,
                type: "object",
                additionalProperties: false,
                properties,
                required: Object.keys(properties)
            },
            contract.schema.definitions ?? {}
        ) as JSONSchema,
        "ActorTypes",
        {
            $refOptions: { resolve: { file: false, http: false } },
            bannerComment: "",
            unknownAny: true,
            additionalProperties: false,
            customName: (schema, key) => {
                const name = schema.title || schema.$id || key
                return (schema.title && kinds.includes(name)) ||
                    ["Connection", "Authorization", "Methods", "Parameters", "ReturnType", "Awaited"].includes(name)
                    ? `${name}Data`
                    : undefined
            }
        }
    )
    const source = ts.createSourceFile("types.ts", code, ts.ScriptTarget.Latest, true)
    const root = source.statements.find(
        statement => ts.isInterfaceDeclaration(statement) && statement.name.text === "ActorTypes"
    ) as ts.InterfaceDeclaration
    const declarations = source.statements.filter(statement => statement !== root)
    const named = new Map(
        declarations
            .filter(
                (statement): statement is ts.InterfaceDeclaration | ts.TypeAliasDeclaration =>
                    ts.isInterfaceDeclaration(statement) || ts.isTypeAliasDeclaration(statement)
            )
            .map(statement => [statement.name.text, statement])
    )
    const main = kinds.map(kind => {
        const declaration = named.get(kind)
        if (declaration) return declaration.getText(source)
        const property = root.members.find(
            member => ts.isPropertySignature(member) && member.name.getText(source) === kind.toLowerCase()
        ) as ts.PropertySignature
        return `export type ${kind} = ${property.type!.getText(source)}`
    })
    const helpers = declarations.filter(statement => !kinds.some(kind => named.get(kind) === statement))
    return {
        code: [...main, ...helpers.map(statement => statement.getText(source))].join("\n\n") + "\n",
        names: [...new Set([...kinds, ...named.keys()])]
    }
}

function inlineAnonymousReferences(
    value: unknown,
    definitions: NonNullable<SocketContract["schema"]["definitions"]>,
    visiting = new Set<string>()
): unknown {
    if (Array.isArray(value)) return value.map(item => inlineAnonymousReferences(item, definitions, visiting))
    if (!value || typeof value !== "object") return value
    const node = value as Record<string, unknown>
    const key =
        typeof node.$ref === "string" && node.$ref.startsWith("#/definitions/")
            ? decodeURIComponent(node.$ref.slice("#/definitions/".length)).replaceAll("~1", "/").replaceAll("~0", "~")
            : undefined
    const definition = key === undefined ? undefined : definitions[key]
    if (
        key !== undefined &&
        definition &&
        typeof definition === "object" &&
        !definition.title &&
        !visiting.has(key) &&
        (/^(Type\d+|Field_.*)$/.test(key) ||
            (typeof definition.type === "string" &&
                ["string", "number", "integer", "boolean", "null"].includes(definition.type)))
    ) {
        const { $ref, ...rest } = node
        return inlineAnonymousReferences({ ...definition, ...rest }, definitions, new Set([...visiting, key]))
    }
    return Object.fromEntries(
        Object.entries(node).map(([key, child]) => [key, inlineAnonymousReferences(child, definitions, visiting)])
    )
}

function proxySource(contracts: readonly SocketContract[]): string {
    const actors = contracts
        .map(
            ({ actorType }) =>
                `[${JSON.stringify(actorType)}]: {} as import("little-actors/proxy").ProxyActor<clients.${actorType}.Metadata>`
        )
        .join(", ")
    const authorization = contracts.map(({ actorType }) => `clients.${actorType}.Authorization`).join(" | ") || "never"
    const exampleActor = contracts[0]?.actorType
    return `${usageComment("The actor and connection details approved by your backend.", exampleActor && `const authorization: ActorAuthorization = { actorType: ${JSON.stringify(exampleActor)}, actorId: "actor-id", metadata }`)}
export type ActorAuthorization = ${authorization}

${usageComment("Allow a frontend connection after your backend checks the user's access.", exampleActor && `const grant = await ActorProxy.handle({ actorType: ${JSON.stringify(exampleActor)}, actorId: "actor-id", metadata })`)}
export class ActorProxy extends $SocketProxy<{
${contracts.map(({ actorType }) => `[${JSON.stringify(actorType)}]: import("little-actors/proxy").ProxyActor<clients.${actorType}.Metadata>`).join("\n")}
}> {
    constructor(options: import("little-actors/proxy").SocketProxyOptions = {}, dependencies: import("little-actors/proxy").SocketProxyDependencies = {}) {
        super({ ${actors} }, options, dependencies)
    }

    handle(authorization: ActorAuthorization): Promise<import("little-actors/proxy").SocketGrant> {
        return super.handle(authorization)
    }

    static handle(authorization: ActorAuthorization, options: import("little-actors/proxy").SocketProxyOptions = {}): Promise<import("little-actors/proxy").SocketGrant> {
        return new ActorProxy(options).handle(authorization)
    }
}
`
}

export { generateTypeScript }
export type { SocketContract }
export type { PublicActorContract }
