export { createActorStub, createActorTransport } from "./stub.js"
export type { ActorRpcTransport, DurableActorsClientOptions } from "./stub.js"
export { ActorInvocationError } from "./errors.js"
export { SocketProxy } from "./proxy.js"
export type { ProxyActor, SocketGrant, SocketProxyDependencies, SocketProxyOptions } from "./proxy.js"
