{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "actors.name" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecret | quote }}
      hosts: [{{ (urlParse .Values.publicUrl).hostname | quote }}]
  rules:
    - host: {{ (urlParse .Values.publicUrl).hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "actors.name" . }}
                port: {number: 7100}
{{- end }}
